name: mervapi
description: A financial API server integrating multiple data sources.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.19.0
  dio: ^5.7.0
  http_parser: ^4.1.0
  meta: ^1.16.0
  shelf: ^1.4.0 
  shelf_router: ^1.1.0 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0